Sprint 1
shreyner/gophkeeper pull request #1
Opened 2023-02-07 19:55 UTC by shreyner

2023-02-11 12:10 UTC, kilchik requested changes

2023-02-11 12:10 UTC, kilchik commented on internal/server/httphandlers/router.go
> +			wr.WriteHeader(200)
Лучше всегда использовать коды из пакета http

2023-02-11 12:10 UTC, kilchik commented on internal/server/httphandlers/router.go
> +				http.Error(wr, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
Не хватает подробного логирования ошибки

2023-02-11 12:10 UTC, kilchik commented on internal/server/httphandlers/router.go
> +		With(chiMiddleware.AllowContentType("application/octet-stream")).
А почему upload не вынес в отдельную функцию, а оставил объявление в инициализации роутера?

2023-02-11 12:10 UTC, kilchik commented on internal/server/rpchandlers/gophkeeper.go
> +		s.log.Error("can't update vault", zap.Error(err))
Тут явно не хватает деталей в логах (id пользователя, возможно какой-то id/key секрета)

2023-02-11 12:10 UTC, kilchik commented on internal/server/server.go
> +var JWTTokenKey = []byte("123")
Все в конфиг

2023-02-12 17:04 UTC, shreyner commented on internal/server/httphandlers/router.go
> +			wr.WriteHeader(200)
Использовал http.StatusOK

2023-02-12 17:04 UTC, shreyner commented on internal/server/httphandlers/router.go
> +				http.Error(wr, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
Добавил лог на ошибку

2023-02-12 17:04 UTC, shreyner commented on internal/server/httphandlers/router.go
> +		With(chiMiddleware.AllowContentType("application/octet-stream")).
Поторопился и для одного обработчика подумал что можно тут оставить

2023-02-12 17:04 UTC, shreyner commented on internal/server/server.go
> +var JWTTokenKey = []byte("123")
Вынес

2023-02-16 16:02 UTC, kilchik requested changes

2023-02-16 16:02 UTC, kilchik commented on internal/client/storage/login-vault_test.go
> +package storage
Для названий файлов, состоящих из нескольких слов, принято использовать "_" или конкатенировать в одно слово

2023-02-16 16:02 UTC, kilchik commented on internal/client/storage/login-vault.go
> +		file, err = os.Create(filePathDB)
Я бы все-таки не ожидал от функции-загрузчика локальных данных создания файла, думаю, это где-то в другом месте должно обрабатываться

2023-02-16 16:02 UTC, kilchik commented on internal/client/storage/login-vault.go
> +		return err
Все ошибки должны быть обернуты с префиксом, иначе сложно локализовать потом причину

2023-02-16 16:02 UTC, kilchik commented on internal/client/storage/login-vault.go
> +func (s *LoginVaultStorage) ViewDataByID(ID uint32) (*LoginSecreteData, error) {
ID->id

2023-02-16 16:02 UTC, kilchik commented on cmd/client/main.go
> +		err = loginVaultStorage.SaveToFile("./data/site-login.db")
Конфиг для клиента пустой, а тут много хардкода, нужно исправить

2023-02-16 16:02 UTC, kilchik commented on cmd/client/main.go
> +	conn, err := grpc.Dial(":3200", grpc.WithTransportCredentials(insecure.NewCredentials()))
А SSL? Ты вроде писал, что добавил

2023-02-16 19:47 UTC, shreyner commented on internal/client/storage/login-vault.go
> +func (s *LoginVaultStorage) ViewDataByID(ID uint32) (*LoginSecreteData, error) {
Переименовал по проекту в аргументах и переменные на id

2023-02-16 19:49 UTC, shreyner commented on internal/client/storage/login-vault_test.go
> +package storage
Понял, переименовал

2023-02-17 07:12 UTC, shreyner commented on cmd/client/main.go
> +	conn, err := grpc.Dial(":3200", grpc.WithTransportCredentials(insecure.NewCredentials()))
Добавил сертификаты для клиента и для сервера.

Для генерации сертификатов надо выполнить команду `make cert`, после в приложении будет браться из переменной окружения

2023-02-17 07:39 UTC, shreyner commented on cmd/client/main.go
> +		err = loginVaultStorage.SaveToFile("./data/site-login.db")
Добавил конфигурацию для клиента через ENV переменные.
Так же добавил флаг для игнорирования проверки tls сертификата

2023-02-19 18:06 UTC, kilchik approved these changes

2023-02-27 09:09 UTC, merged